services:
  mysql:
    image: mysql:8.0
    container_name: products_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: products_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql

  backend:
    image: abdallahhamrouni/products-backend:1.0
    build:
      context: ./back-product
      dockerfile: Dockerfile
    container_name: products_backend
    restart: unless-stopped
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: products_db
      DB_PORT: 3306
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    image: abdallahhamrouni/products-frontend:1.0
    build:
      context: ./front-product
      dockerfile: Dockerfile
    container_name: products_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
